//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class NLog
    {
        public static object LogManager { get; internal set; }
        public int id { get; set; }
        public System.DateTime timestamp { get; set; }
        public string level { get; set; }
        public string message { get; set; }
        public string exception { get; set; }
    }
}
